### ISSUE TITLE
Detected package downgrade Exception with GroupDocs.Viewer.UI.SelfHost.Api 6.0.11

### ISSUE THREAD

**Issue by ManuelHaas** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI#39]
Hi,

the following error will be thrown when using GroupDocs.Viewer.UI.SelfHost.Api 6.0.10 and 6.0.11 with a current (7.0.4) .NET Core Web App:

`````csharp
Error: Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. 
 ToSec.DataAccess -> GroupDocs.Viewer.UI.SelfHost.Api 6.0.11 -> Microsoft.AspNetCore.Mvc.Core 2.2.5 -> Microsoft.Extensions.DependencyModel 2.1.0 -> Microsoft.DotNet.PlatformAbstractions 2.1.0 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.IO.FileSystem.Primitives (>= 4.3.0) 
 ToSec.DataAccess -> GroupDocs.Viewer.UI.SelfHost.Api 6.0.11 -> Microsoft.AspNetCore.Mvc.Core 2.2.5 -> Microsoft.Extensions.DependencyModel 2.1.0 -> Microsoft.DotNet.PlatformAbstractions 2.1.0 -> System.IO.FileSystem 4.0.1 -> System.IO.FileSystem.Primitives (>= 4.0.1)
`````

This is a regression:  #19 

**Environment**:

- .NET Core version 7.0.4
- GroupDocs.Viewer.UI version 6.0.11
- Operative system: Win11
- Others: VS 17.5.3

**Comment by vyacheslav-prokopenko** [comment]
Hi, @ManuelHaas . Could you please attach .sln and .csproj files of the solution and the project ?

**Comment by ManuelHaas** [comment]
Hi, attached you will find the project file.

[Project.csproj.txt](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/files/11171334/Project.csproj.txt)

**Comment by vyacheslav-prokopenko** [comment]
Hi, @ManuelHaas  It seems the problem with runtime package dependencies 
System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.IO.FileSystem.Primitives (>= 4.3.0)
System.IO.FileSystem 4.0.1 -> System.IO.FileSystem.Primitives (>= 4.0.1)

and NU1605 is not suppressed within solution

Plz try
1. suppress NU1605 (it is the default setting) 
2. 
![scr](https://user-images.githubusercontent.com/106738048/230623924-237fa592-4b5e-40a0-bdd1-9db172f2eb66.png)

3.

**Comment by ManuelHaas** [comment]
Thank you for the recommendations.
@1: I will not change the default settings because of the error.
@2: This is the workaround your colleague recommended the last time the problem occurred. I have set this temporarily.
However, the problem still does not occur with version 6.0.5. The error has only occurred since the update.

**Comment by vyacheslav-prokopenko** [comment]
Hi, @ManuelHaas thank you for feedback. Could you please provide some sample project where I can reproduce the issue? Actually I've been trying to create some sample many times but all was working fine with the given project settings.

**Comment by ManuelHaas** [comment]
Hi, @vyacheslav-prokopenko I didn't know that the error had anything to do with my project settings. Here is the base project that is referenced by the other project (which I have already uploaded) that is causing the error.

[base.csproj.txt](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/files/11212830/base.csproj.txt)

**Comment by vyacheslav-prokopenko** [comment]
Hello, @ManuelHaas . Still can not reproduce the issue locally. Could you please help to reproduce with attached project (solution is located in ClassLibrary1 folder)
[Base.zip](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/files/11222907/Base.zip)

**Comment by vladimir-litvinchik** [comment]
@ManuelHaas 

Did you manage to resolve this issue?

**Comment by ManuelHaas** [comment]
@vladimir-litvinchik like last time I referenced System.IO.FileSystem.Primitives directly in the project. I assume the problem still exists. Unfortunately I don't have the time to create a sample project.

**Comment by vladimir-litvinchik** [comment]
@ManuelHaas 

Got it, thank you for the feedback.
