### ISSUE TITLE
EXIF metadata is not taken into account when showing jpg

### ISSUE THREAD

**Issue by ManuelHaas** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI#51]
**What happened**:
When displaying jpg files, the EXIF data that indicates whether the image needs to be rotated is not taken into account. 

**What you expected to happen**:
The EXIF data is taken into account and the image file is displayed correctly.

**How to reproduce it**:
You can test the problem with your demo: https://products.groupdocs.app/viewer/total

Upload the jpg file that is attached this bug report and you will see that it is upside down. Open the jpg in a Windows viewer and the image will be displayed correctly, as the EXIF information is taken into account here.

**Environment**:
- .NET Core version 7.0.14
- GroupDocs.Viewer.UI version 6.0.16

![20231127_125852](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/assets/10881695/80e0c2d8-ca74-4cf0-ab41-9bb1f0be5641)

**Comment by vladimir-litvinchik** [comment]
@ManuelHaas 

Thank you for attaching the sample jpg image. We'll investigate this issue. As soon as we have any new results we'll let you know.

**Comment by ManuelHaas** [comment]
Any news on that? Were you able to reproduce the bug?

**Comment by vladimir-litvinchik** [comment]
@ManuelHaas 

The issue has been fixed. Please update the `GroupDocs.Viewer.UI.SelfHost.Api` to version `6.0.20`. You should now be able to view the source file correctly.

<img width="960" alt="rotated-jpeg" src="https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/assets/35294201/ef37ecb1-a982-4390-9240-4f9a93758d84">

**Comment by vladimir-litvinchik** [comment]
@ManuelHaas 

Please update the `GroupDocs.Viewer.UI.SelfHost.Api` to version `6.0.21` that references [GroupDocs.Viewer for .NET 24.1.1](https://releases.groupdocs.com/viewer/net/release-notes/2024/groupdocs-viewer-for-net-24-1-1-release-notes/) hot-fix version. It fixes runtime exception `Could not load file or assembly ‘System.Drawing.Common, Version=6.0.0.0`.
