### ISSUE TITLE
RangeError: Set maximum size exceeded

### ISSUE THREAD

**Issue by ManuelHaas** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI#54]
When displaying documents via GroupDocs a console log error appears twice in main.js. However, it seems that the functionality of the GroupDocs Viewer is not affected by this. 

What could be the cause?

![image](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/assets/10881695/06318a11-56d2-4a57-8108-fa0b9ece2232)

- .NET Core version 7.0.15
- GroupDocs.Viewer.UI version 6.0.16

**Comment by vladimir-litvinchik** [comment]
@ManuelHaas 

Thank you for reporting this issue but we're not going to fix it as the new Angular UI will replace this one next month.
