### ISSUE TITLE
How to specify a file during operation instead of a directory at startup.

### ISSUE THREAD

**Issue by RANSUROTTO** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI#57]
As the title says, I don't want to specify the attachment directory at startup, nor do I want to be able to select other files in the view.

I want to display the UI interface on a certain page, pass in the attachment address or attachment file stream, and customize the toolbar in the process.

**Comment by vladimir-litvinchik** [comment]
@RANSUROTTO 

You can customize the client [client app](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/blob/master/src/GroupDocs.Viewer.UI/client/). The key components are:
* [app.component.html](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/blob/master/src/GroupDocs.Viewer.UI/client/src/app/app.component.html);
* [app.component.ts](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/blob/master/src/GroupDocs.Viewer.UI/client/src/app/app.component.ts);
* and [index.html](https://github.com/groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI/blob/master/src/GroupDocs.Viewer.UI/client/src/index.html).

The app expects `<app-root></app-root>` tag that can be put in some place on your page.  

To open any file you'll need making a proxy call to [selectFile](https://github.com/groupdocs-total/GroupDocs.Total-Angular/blob/master/libs/viewer/src/lib/viewer-app.component.ts#L380) method and pass the file ID by using which you can read a file using custom file storage. 

Another option can be loading a complete page in <iframe> so you can keep the original index.html file but seems to be less flexible.
