### ISSUE TITLE
Excel documents heavily impacted by print breaks

### ISSUE THREAD

**Issue by brendancolebf** [groupdocs-viewer/GroupDocs.Viewer-for-.NET-UI#59]
**What happened**:
Excel documents are broken up by their page breaks. Each page is rendered with a button along the bottom row as if they're sheets, but these are duplicated for each page of each sheet. These pages also appear to not render beyond the 2nd or 3rd.

**What you expected to happen**:
If possible, Excel documents should be rendered by sheet, rather than by print margins. If this can't be achieved, the experience should be improved to make it more obvious you're previewing by page rather than by sheet.

It should also be possible to preview more than just the first few pages.

**How to reproduce it**:
I've attached a small Excel document I created to reproduce the issue. Within Excel, you can see by enabling Page Layout > Gridlines > Print that there's a page break on each column. This is also apparent by checking the print preview in File > Print.
[Excel Test.xlsx](https://github.com/user-attachments/files/17037052/Excel.Test.xlsx)

When previewing, it will be rendered with a tab for each page, and in my testing, occasionally the 4th page will get stuck on Loading.
![image](https://github.com/user-attachments/assets/497d742e-97c6-4f92-a270-42407a4ff654)

**Source code sample**:
N/A

**Environment**:

- .NET Core version: 8
- GroupDocs.Viewer.UI version: 6.0.22
- Operative system: Windows 11, Kubernetes

**Comment by vladimir-litvinchik** [comment]
@brendancolebf 

Thank you for reporting this issue.  To display a complete worksheet you set the following configuration in your `Program.cs` file.

```
builder.Services
        .AddControllers()
        .AddGroupDocsViewerSelfHostApi(config =>
        {
            config.SetLicensePath("c://license//GroupDocs.Viewer.lic");

            config.ConfigureHtmlViewOptions(viewOptions => {
                viewOptions.SpreadsheetOptions = SpreadsheetOptions.ForOnePagePerSheet();
                viewOptions.SpreadsheetOptions.RenderGridLines = true;
                viewOptions.SpreadsheetOptions.RenderHeadings = true;
            });
        })
        .AddLocalStorage("./Files")
        .AddLocalCache("./Cache");
```

I have added the following lines

```
config.ConfigureHtmlViewOptions(viewOptions => {
    viewOptions.SpreadsheetOptions = SpreadsheetOptions.ForOnePagePerSheet(); // render complete worksheet
    viewOptions.SpreadsheetOptions.RenderGridLines = true; // render grid lines 
    viewOptions.SpreadsheetOptions.RenderHeadings = true; // render headings
});
```

Make sure to cleanup `Cache` folder and run the app one more time with `dotnet run`.
Select the file and the output will be the following:

<img width="959" alt="viewer-three-worksheets" src="https://github.com/user-attachments/assets/a14a8826-527e-4c05-a38d-017fcae95db3">

Sample app: [sample-viewer-app.zip](https://github.com/user-attachments/files/17041781/sample-viewer-app.zip)

We'll consider enabling this options by default in future version.

To test all the features you can get a temporary license. There are a couple of steps that should be perform:

1. Go to https://purchase.groupdocs.com/buy and select Product Family
<img width="959" alt="select-product-family" src="https://github.com/user-attachments/assets/4dfa6cf4-b36d-4c7d-b73c-ac91a3bf4d4c">

 2. Click `Add to Cart` button.
<img width="959" alt="click-add-to-cart" src="https://github.com/user-attachments/assets/7ecda841-b35d-49b0-93d7-6aa669e88ade">

3. Create account and continue after you log in.

4. Click `Proceed` on the next page.
<img width="959" alt="click-proceed" src="https://github.com/user-attachments/assets/3439c5cc-2394-436f-994d-090ae77ee005">

5. Enter contact information and make sure to enter proper email address. Click `Get a temporary license`.
<img width="959" alt="click-get-temporary-license" src="https://github.com/user-attachments/assets/a629d818-57c8-4c4f-a8d3-3c9b2fbeb20c">

6. Check you mail box.

Now you can set a proper path to the temporary license in `Program.cs` file e.g.

```
config.SetLicensePath("c://license//GroupDocs.Viewer.lic");
```

Let us know if you have any questions.

**Comment by vladimir-litvinchik** [comment]
@brendancolebf 

No problem! Let us know if you have any questions.

Have a nice day!
